### ISSUE TITLE
Consider using prefers-color-scheme to provide an automatic light/dark selection

### ISSUE THREAD

**Issue by Kernald** [bake/solar-theme-hugo#2]
The `prefers-color-scheme` media query is [supported by all major browsers](https://caniuse.com/#search=prefers-color-scheme), and switching automatically from light to dark would be a nice touch. It looks like it would mostly be a matter of loading conditionally one CSS file or the other, with something like that:

```
<script>
  // Fallback if prefers-color-scheme is not supported
  if (window.matchMedia('(prefers-color-scheme)').media === 'not all') {
    document.documentElement.style.display = 'none';
    document.head.insertAdjacentHTML(
        'beforeend',
        '<link rel="stylesheet" href="/light.css" onload="document.documentElement.style.display = ``">'
    );
  }
</script>
<link rel="stylesheet" href="/dark.css" media="(prefers-color-scheme: dark)">
<link rel="stylesheet" href="/light.css" media="(prefers-color-scheme: no-preference), (prefers-color-scheme: light)">
<link rel="stylesheet" href="/style.css">
```

**Comment by bake** [comment]
Great idea! I've created a branch [prefers-color-scheme](https://github.com/bake/solar-theme-hugo/tree/prefers-color-scheme) and switched to SCSS. Would this work for you?

**Comment by Kernald** [comment]
Looks great indeed, thanks!
