### ISSUE TITLE
Broken demo page.

### ISSUE THREAD

**Issue by udit-001** [bake/solar-theme-hugo#4]
Your demo page seems to be not working correctly on the gohugo site.

**Comment by bake** [comment]
Are you sure? [It looks fine to me.](https://themes.gohugo.io/theme/solar-theme-hugo/)

**Comment by udit-001** [comment]
Well, Here's how it looks to me on my browser (ungoogled-chromium)
![Broken](https://i.postimg.cc/xjsMpZHg/solar-theme.png)

**Comment by bake** [comment]
There are no external dependencies so it should look the same in every browser. Could you please see if the console in your dev tools is reporting something?

**Comment by bake** [comment]
There is [an issue on hugoThemes](https://github.com/gohugoio/hugoThemes/issues/761) describing the problem. Thanks for the heads up! I'll close this issue once the other one is done.

**Comment by udit-001** [comment]
So there was something up with the site after all? Guess I don't have to switch my browser for now :+1:
