### ISSUE TITLE
Reference to localhost

### ISSUE THREAD

**Issue by githubr** [bake/solar-theme-hugo#5]
Hi, thank you for sharing this theme.

I have tried to install it but I have issues that the CSS is being referred using `localhost` which broke the visual.

So, I use the config.toml that is included in the exampleSite and start the site:

`hugo server --port 3000 --bind "0.0.0.0"`

I got the following from Firefox debug tool. The site loads and I can see content, however the stylesheet is broken being served using `localhost`. I don't know if this is relevant, I install it on raspberrypi which uses ARM architecture.

![image](https://user-images.githubusercontent.com/3155247/74231393-39a3af00-4d12-11ea-8920-6ecc848ef388.png)

**Comment by bake** [comment]
Hi, thanks for the issue, though I'm not sure if I understand it correctly. Are you trying to access your site with an URL that is not `localhost` or `127.0.0.1`? As far as I know, `hugo serve` uses absolute paths that can be modified using the `--baseURL` flag. (If you build your site using just `hugo`, you usually get relative paths. It wouldn't be a problem there. However, if you don't have another webserver on your Raspi running, Hugos built in one might actually be a great idea.)

For example:
```bash
$ hugo server --port 3000 --bind "0.0.0.0" --baseURL https://foobar
```

**Comment by githubr** [comment]
Awesome ... all working fine now. I didn't know there is --baseURL param.

Thanks for your help.
