### ISSUE TITLE
List-style bullet does not exist

### ISSUE THREAD

**Issue by gripfx** [bake/solar-theme-hugo#6]
Hi,
Not sure if I am missing something (font-wise or otherwise). The unordered lists show up as numbered lists. You can see this on the sample page as well at https://themes.gohugo.io//theme/solar-theme-hugo/post/markdown-syntax/.
![image](https://user-images.githubusercontent.com/13381974/113484094-7abecb80-949e-11eb-9d35-182408b1840f.png)

From browsing MDN, the solution seems to be to use "disc" for unordered lists. 

Thanks.

**Comment by bake** [comment]
Thank you for the issue! I never noticed this. Should be fixed in 97632b71c2410a22269fd0456f61ae51adfd1063, please let me know if it works :)

**Comment by gripfx** [comment]
Yes that worked perfectly. Thanks!
